### PR TITLE
Added Support download from URL

### PR DESCRIPTION
**Pull request by alamia442**

### CODE REVIEW

**Comment by zeroone2numeral2** [comment]
Sorry, I do not understand what this jackett.torrent url is - can you explain it shortly?

**Comment by alamia442** [comment]
qbittorrent can add download from url like 
1. https://sample.jackett.com/dl/1337x/?jackett_apikey=
2. https://yts.mx/torrent/download/49A562A3D527C07658B8D824891D32AF0A792204
3. https://psarips.uk/torrents/2020/10/The.Walking.Dead.World.Beyond.S01E06.Shadow.Puppets.720p.WEBRip.2CH.x265.HEVC-PSA-298980.torrent

updater.add_handler(MessageHandler(Filters.text & Filters.regex(r"^https?:\/\/.*(jackett|\.torren|\/torrent).*"), add_from_url))

**Comment by zeroone2numeral2** [comment]
Ah, I see. The regex is really broad though, so it will match with a lot of urls. As far as I know, qbittorrent's api will return a positive response even when a magnet link is not valid. Did you try to test what the request returns when you pass a generic http url?

**Comment by alamia442** [comment]
I have use without regex before, work perfect but for private use only
I am add regex yesterday and work good
bot not reply on url http/https://google.com and I think user will send only http/s link support by qbt :)

**Pull request merged**
